version: 1

formatters:
  console:
    format: '%(asctime)s - %(levelname)s - %(name)s[%(lineno)d] - %(message)s'
  file:
    format: '%(asctime)s - %(levelname)s - %(name)s[%(lineno)d] - %(message)s'

handlers:
  console_handler:
    class: logging.StreamHandler
    level: INFO
    formatter: console
    stream: ext://sys.stdout
  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: file
    filename: application.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

loggers:
  logger:
    level: INFO
    handlers: [console_handler, file_handler]
    propagate: no

root:
  level: INFO
  handlers: [console_handler, file_handler]